--
-- PostgreSQL database dump
--

\restrict mXppParej3gzppNyhkf5d1NZHqKdZlYpynQpmcgTZqrhzjYLGNpFHaXJ1ULNigW

-- Dumped from database version 17.8 (9c8634e)
-- Dumped by pg_dump version 17.10 (Ubuntu 17.10-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administrator; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.administrator (
    id_korisnik integer NOT NULL
);


ALTER TABLE public.administrator OWNER TO neondb_owner;

--
-- Name: dogadaj; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.dogadaj (
    id_dogadaj integer NOT NULL,
    naziv_dogadaja character varying,
    datum_odrzavanja timestamp without time zone,
    id_korisnik_udruga integer,
    id_korisnik_admin integer,
    id_centar integer,
    id_teren character varying
);


ALTER TABLE public.dogadaj OWNER TO neondb_owner;

--
-- Name: dogadaj_id_dogadaj_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.dogadaj ALTER COLUMN id_dogadaj ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dogadaj_id_dogadaj_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: korisnik; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.korisnik (
    id_korisnik integer NOT NULL,
    ime character varying,
    prezime character varying,
    email character varying,
    tip_korisnika character varying
);


ALTER TABLE public.korisnik OWNER TO neondb_owner;

--
-- Name: korisnik_id_korisnik_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.korisnik ALTER COLUMN id_korisnik ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.korisnik_id_korisnik_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mjesto; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.mjesto (
    id_mjesto integer NOT NULL,
    naziv_mjesta character varying,
    postanski_broj character varying
);


ALTER TABLE public.mjesto OWNER TO neondb_owner;

--
-- Name: mjesto_id_mjesto_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.mjesto ALTER COLUMN id_mjesto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mjesto_id_mjesto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: obavijest; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.obavijest (
    id_obavijesti integer NOT NULL,
    tekst character varying,
    datum_obavijesti timestamp without time zone,
    id_korisnik_vlasnik integer,
    id_korisnik_admin integer
);


ALTER TABLE public.obavijest OWNER TO neondb_owner;

--
-- Name: obavijest_id_obavijesti_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.obavijest ALTER COLUMN id_obavijesti ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.obavijest_id_obavijesti_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: preferencija; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.preferencija (
    id_korisnik integer NOT NULL,
    id_sport integer NOT NULL
);


ALTER TABLE public.preferencija OWNER TO neondb_owner;

--
-- Name: rezervacija; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.rezervacija (
    id_korisnik integer NOT NULL,
    id_centar integer NOT NULL,
    id_teren character varying NOT NULL,
    vrijeme_pocetka timestamp without time zone NOT NULL,
    vrijeme_zavrsetka timestamp without time zone,
    id_rezervacija bigint NOT NULL
);


ALTER TABLE public.rezervacija OWNER TO neondb_owner;

--
-- Name: rezervacija_id_rezervacija_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

CREATE SEQUENCE public.rezervacija_id_rezervacija_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rezervacija_id_rezervacija_seq OWNER TO neondb_owner;

--
-- Name: rezervacija_id_rezervacija_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: neondb_owner
--

ALTER SEQUENCE public.rezervacija_id_rezervacija_seq OWNED BY public.rezervacija.id_rezervacija;


--
-- Name: sport; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.sport (
    id_sport integer NOT NULL,
    naziv_sporta character varying
);


ALTER TABLE public.sport OWNER TO neondb_owner;

--
-- Name: sport_id_sport_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.sport ALTER COLUMN id_sport ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sport_id_sport_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sportas_rekreativac; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.sportas_rekreativac (
    id_korisnik integer NOT NULL
);


ALTER TABLE public.sportas_rekreativac OWNER TO neondb_owner;

--
-- Name: sportska_udruga; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.sportska_udruga (
    id_korisnik integer NOT NULL,
    naziv_udruge character varying
);


ALTER TABLE public.sportska_udruga OWNER TO neondb_owner;

--
-- Name: sportski_centar; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.sportski_centar (
    id_centar integer NOT NULL,
    naziv_centra character varying,
    adresa character varying,
    id_mjesto integer,
    id_vlasnik integer,
    radno_vrijeme_tjedan_od time without time zone,
    radno_vrijeme_tjedan_do time without time zone,
    radno_vrijeme_vikend_od time without time zone,
    radno_vrijeme_vikend_do time without time zone
);


ALTER TABLE public.sportski_centar OWNER TO neondb_owner;

--
-- Name: sportski_centar_id_centar_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.sportski_centar ALTER COLUMN id_centar ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sportski_centar_id_centar_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teren; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.teren (
    id_centar integer NOT NULL,
    id_teren character varying NOT NULL,
    cijena numeric,
    id_sport integer
);


ALTER TABLE public.teren OWNER TO neondb_owner;

--
-- Name: vlasnik_centra; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.vlasnik_centra (
    id_korisnik integer NOT NULL
);


ALTER TABLE public.vlasnik_centra OWNER TO neondb_owner;

--
-- Name: rezervacija id_rezervacija; Type: DEFAULT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.rezervacija ALTER COLUMN id_rezervacija SET DEFAULT nextval('public.rezervacija_id_rezervacija_seq'::regclass);


--
-- Name: administrator administrator_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.administrator
    ADD CONSTRAINT administrator_pkey PRIMARY KEY (id_korisnik);


--
-- Name: dogadaj dogadaj_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.dogadaj
    ADD CONSTRAINT dogadaj_pkey PRIMARY KEY (id_dogadaj);


--
-- Name: korisnik korisnik_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.korisnik
    ADD CONSTRAINT korisnik_pkey PRIMARY KEY (id_korisnik);


--
-- Name: mjesto mjesto_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.mjesto
    ADD CONSTRAINT mjesto_pkey PRIMARY KEY (id_mjesto);


--
-- Name: obavijest obavijest_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.obavijest
    ADD CONSTRAINT obavijest_pkey PRIMARY KEY (id_obavijesti);


--
-- Name: rezervacija pk_rezervacija; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.rezervacija
    ADD CONSTRAINT pk_rezervacija PRIMARY KEY (id_rezervacija);


--
-- Name: preferencija preferencija_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.preferencija
    ADD CONSTRAINT preferencija_pkey PRIMARY KEY (id_korisnik, id_sport);


--
-- Name: sport sport_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sport
    ADD CONSTRAINT sport_pkey PRIMARY KEY (id_sport);


--
-- Name: sportas_rekreativac sportas_rekreativac_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sportas_rekreativac
    ADD CONSTRAINT sportas_rekreativac_pkey PRIMARY KEY (id_korisnik);


--
-- Name: sportska_udruga sportska_udruga_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sportska_udruga
    ADD CONSTRAINT sportska_udruga_pkey PRIMARY KEY (id_korisnik);


--
-- Name: sportski_centar sportski_centar_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sportski_centar
    ADD CONSTRAINT sportski_centar_pkey PRIMARY KEY (id_centar);


--
-- Name: teren teren_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.teren
    ADD CONSTRAINT teren_pkey PRIMARY KEY (id_centar, id_teren);


--
-- Name: rezervacija uq_rezervacija_teren_pocetak; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.rezervacija
    ADD CONSTRAINT uq_rezervacija_teren_pocetak UNIQUE (id_centar, id_teren, vrijeme_pocetka);


--
-- Name: vlasnik_centra vlasnik_centra_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.vlasnik_centra
    ADD CONSTRAINT vlasnik_centra_pkey PRIMARY KEY (id_korisnik);


--
-- Name: idx_rezervacija_teren_interval; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_rezervacija_teren_interval ON public.rezervacija USING btree (id_centar, id_teren, vrijeme_pocetka, vrijeme_zavrsetka);


--
-- Name: administrator administrator_id_korisnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.administrator
    ADD CONSTRAINT administrator_id_korisnik_fkey FOREIGN KEY (id_korisnik) REFERENCES public.korisnik(id_korisnik);


--
-- Name: dogadaj dogadaj_id_centar_id_teren_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.dogadaj
    ADD CONSTRAINT dogadaj_id_centar_id_teren_fkey FOREIGN KEY (id_centar, id_teren) REFERENCES public.teren(id_centar, id_teren);


--
-- Name: dogadaj dogadaj_id_korisnik_admin_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.dogadaj
    ADD CONSTRAINT dogadaj_id_korisnik_admin_fkey FOREIGN KEY (id_korisnik_admin) REFERENCES public.administrator(id_korisnik);


--
-- Name: dogadaj dogadaj_id_korisnik_udruga_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.dogadaj
    ADD CONSTRAINT dogadaj_id_korisnik_udruga_fkey FOREIGN KEY (id_korisnik_udruga) REFERENCES public.sportska_udruga(id_korisnik);


--
-- Name: obavijest obavijest_id_korisnik_admin_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.obavijest
    ADD CONSTRAINT obavijest_id_korisnik_admin_fkey FOREIGN KEY (id_korisnik_admin) REFERENCES public.administrator(id_korisnik);


--
-- Name: obavijest obavijest_id_korisnik_vlasnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.obavijest
    ADD CONSTRAINT obavijest_id_korisnik_vlasnik_fkey FOREIGN KEY (id_korisnik_vlasnik) REFERENCES public.vlasnik_centra(id_korisnik);


--
-- Name: preferencija preferencija_id_korisnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.preferencija
    ADD CONSTRAINT preferencija_id_korisnik_fkey FOREIGN KEY (id_korisnik) REFERENCES public.korisnik(id_korisnik);


--
-- Name: preferencija preferencija_id_sport_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.preferencija
    ADD CONSTRAINT preferencija_id_sport_fkey FOREIGN KEY (id_sport) REFERENCES public.sport(id_sport);


--
-- Name: rezervacija rezervacija_id_centar_id_teren_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.rezervacija
    ADD CONSTRAINT rezervacija_id_centar_id_teren_fkey FOREIGN KEY (id_centar, id_teren) REFERENCES public.teren(id_centar, id_teren);


--
-- Name: rezervacija rezervacija_id_korisnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.rezervacija
    ADD CONSTRAINT rezervacija_id_korisnik_fkey FOREIGN KEY (id_korisnik) REFERENCES public.sportas_rekreativac(id_korisnik);


--
-- Name: sportas_rekreativac sportas_rekreativac_id_korisnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sportas_rekreativac
    ADD CONSTRAINT sportas_rekreativac_id_korisnik_fkey FOREIGN KEY (id_korisnik) REFERENCES public.korisnik(id_korisnik);


--
-- Name: sportska_udruga sportska_udruga_id_korisnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sportska_udruga
    ADD CONSTRAINT sportska_udruga_id_korisnik_fkey FOREIGN KEY (id_korisnik) REFERENCES public.korisnik(id_korisnik);


--
-- Name: sportski_centar sportski_centar_id_mjesto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sportski_centar
    ADD CONSTRAINT sportski_centar_id_mjesto_fkey FOREIGN KEY (id_mjesto) REFERENCES public.mjesto(id_mjesto);


--
-- Name: sportski_centar sportski_centar_id_vlasnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sportski_centar
    ADD CONSTRAINT sportski_centar_id_vlasnik_fkey FOREIGN KEY (id_vlasnik) REFERENCES public.vlasnik_centra(id_korisnik);


--
-- Name: teren teren_id_centar_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.teren
    ADD CONSTRAINT teren_id_centar_fkey FOREIGN KEY (id_centar) REFERENCES public.sportski_centar(id_centar);


--
-- Name: teren teren_id_sport_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.teren
    ADD CONSTRAINT teren_id_sport_fkey FOREIGN KEY (id_sport) REFERENCES public.sport(id_sport);


--
-- Name: vlasnik_centra vlasnik_centra_id_korisnik_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.vlasnik_centra
    ADD CONSTRAINT vlasnik_centra_id_korisnik_fkey FOREIGN KEY (id_korisnik) REFERENCES public.korisnik(id_korisnik);


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

\unrestrict mXppParej3gzppNyhkf5d1NZHqKdZlYpynQpmcgTZqrhzjYLGNpFHaXJ1ULNigW

